"""项目初始化

Revision ID: 035f890620ba
Revises: 9c84f9574b4d
Create Date: 2025-06-11 23:15:16.097194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035f890620ba'
down_revision = '9c84f9574b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
