"""empty message

Revision ID: 621ad36ff901
Revises: b9c7f53ad904
Create Date: 2026-02-01 21:08:50.652381

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '621ad36ff901'
down_revision = 'b9c7f53ad904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
