"""项目初始化

Revision ID: 9c84f9574b4d
Revises: 
Create Date: 2025-06-11 01:07:22.814117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c84f9574b4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_app_id')
    )
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.create_index('idx_app_account_id', ['account_id'], unique=False)

    with op.batch_alter_table('llmops_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uniq_email'))

    op.drop_table('llmops_account')
    with op.batch_alter_table('llmops_app_dataset_join', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_app_dataset'))
        batch_op.drop_index(batch_op.f('idx_app_id'))
        batch_op.drop_index(batch_op.f('idx_dataset_id'))

    op.drop_table('llmops_app_dataset_join')
    with op.batch_alter_table('llmops_chat_dialog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tenant_id'))

    op.drop_table('llmops_chat_dialog')
    with op.batch_alter_table('llmops_dataset_query', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_dataset_id'))
        batch_op.drop_index(batch_op.f('idx_source_app_id'))

    op.drop_table('llmops_dataset_query')
    with op.batch_alter_table('llmops_api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_id'))
        batch_op.drop_index(batch_op.f('uniq_api_key'))

    op.drop_table('llmops_api_key')
    with op.batch_alter_table('llmops_process_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_id'))
        batch_op.drop_index(batch_op.f('idx_dataset_id'))
        batch_op.drop_index(batch_op.f('idx_mode'))

    op.drop_table('llmops_process_rule')
    with op.batch_alter_table('llmops_dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_id'))
        batch_op.drop_index(batch_op.f('idx_account_name'))
        batch_op.drop_index(batch_op.f('idx_name'))

    op.drop_table('llmops_dataset')
    with op.batch_alter_table('llmops_app_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_app_config_type'))

    op.drop_table('llmops_app_config')
    op.drop_table('llmops_upload_file')
    with op.batch_alter_table('llmops_chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_role'))
        batch_op.drop_index(batch_op.f('idx_tenant_id'))

    op.drop_table('llmops_chat_history')
    with op.batch_alter_table('llmops_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_id'))
        batch_op.drop_index(batch_op.f('idx_dataset_id'))
        batch_op.drop_index(batch_op.f('idx_document_id'))
        batch_op.drop_index(batch_op.f('idx_hash'))
        batch_op.drop_index(batch_op.f('idx_node_id'))
        batch_op.drop_index(batch_op.f('idx_status'))

    op.drop_table('llmops_segment')
    with op.batch_alter_table('llmops_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_app_id'))
        batch_op.drop_index(batch_op.f('idx_created_by'))

    op.drop_table('llmops_message')
    with op.batch_alter_table('llmops_api_tool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_id'))
        batch_op.drop_index(batch_op.f('idx_account_name'))
        batch_op.drop_index(batch_op.f('idx_name'))

    op.drop_table('llmops_api_tool')
    with op.batch_alter_table('llmops_workflow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('api_key'))
        batch_op.drop_index(batch_op.f('idx_account_id'))

    op.drop_table('llmops_workflow')
    with op.batch_alter_table('llmops_api_tool_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_id'))
        batch_op.drop_index(batch_op.f('idx_account_name'))
        batch_op.drop_index(batch_op.f('idx_name'))

    op.drop_table('llmops_api_tool_provider')
    with op.batch_alter_table('llmops_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_app_id'))
        batch_op.drop_index(batch_op.f('idx_is_delete'))

    op.drop_table('llmops_conversation')
    with op.batch_alter_table('llmops_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_id'))
        batch_op.drop_index(batch_op.f('idx_batch'))
        batch_op.drop_index(batch_op.f('idx_dataset_id'))
        batch_op.drop_index(batch_op.f('idx_enabled'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_upload_file_id'))

    op.drop_table('llmops_document')
    with op.batch_alter_table('llmops_app', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_id'))
        batch_op.drop_index(batch_op.f('idx_name'))
        batch_op.drop_index(batch_op.f('idx_status'))

    op.drop_table('llmops_app')
    with op.batch_alter_table('llmops_keyword_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dataset_id'))

    op.drop_table('llmops_keyword_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmops_keyword_table',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('dataset_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的知识库id'),
    sa.Column('keyword_table', mysql.JSON(), server_default=sa.text('(json_object())'), nullable=False, comment='关键词表'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='关键词配置表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='关键词配置表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_keyword_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('llmops_app',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='账号id'),
    sa.Column('published_app_config_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='已发布配置id'),
    sa.Column('drafted_app_config_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='调试会话id'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='应用名称'),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='应用图标'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='应用描述'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), server_default=sa.text("''"), nullable=False, comment='应用状态'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI应用表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='AI应用表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_app', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_account_id'), ['account_id'], unique=False)

    op.create_table('llmops_document',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的用户id'),
    sa.Column('dataset_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的知识库id'),
    sa.Column('upload_file_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的文件id'),
    sa.Column('process_rule_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='处理规则id'),
    sa.Column('batch', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='文档处理批次'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='文档名字'),
    sa.Column('position', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='文档位置'),
    sa.Column('character_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='文档总字符'),
    sa.Column('token_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='文档token数'),
    sa.Column('processing_started_at', mysql.TIMESTAMP(), nullable=True, comment='开始处理时间'),
    sa.Column('parsing_completed_at', mysql.TIMESTAMP(), nullable=True, comment='解析结束时间'),
    sa.Column('splitting_completed_at', mysql.TIMESTAMP(), nullable=True, comment='分割结束时间'),
    sa.Column('index_completed_at', mysql.TIMESTAMP(), nullable=True, comment='索引结束时间'),
    sa.Column('completed_at', mysql.TIMESTAMP(), nullable=True, comment='构建完成时间'),
    sa.Column('stopped_at', mysql.TIMESTAMP(), nullable=True, comment='停止时间'),
    sa.Column('error', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='错误日志'),
    sa.Column('enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='是否启用'),
    sa.Column('disabled_at', mysql.TIMESTAMP(), nullable=True, comment='人为禁用时间'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("''"), nullable=False, comment='状态'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文档',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='文档',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_upload_file_id'), ['upload_file_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('idx_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_batch'), ['batch'], unique=False)
        batch_op.create_index(batch_op.f('idx_account_id'), ['account_id'], unique=False)

    op.create_table('llmops_conversation',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('app_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='应用id'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='会话名称'),
    sa.Column('summary', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='会话概要'),
    sa.Column('is_pinned', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否置顶'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否删除'),
    sa.Column('invoke_from', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='来源'),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='创建会话的id'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='会话表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='会话表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_is_delete'), ['is_delete'], unique=False)
        batch_op.create_index(batch_op.f('idx_app_id'), ['app_id'], unique=False)

    op.create_table('llmops_api_tool_provider',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的用户id'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='提供商名称'),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='提供商图标'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='应用描述'),
    sa.Column('openapi_schema', mysql.JSON(), nullable=True, comment='描述规范'),
    sa.Column('headers', mysql.JSON(), nullable=True, comment='提供商对应的请求头'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='API工具提供者',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='API工具提供者',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_api_tool_provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_account_name'), ['account_id', 'name'], unique=True)
        batch_op.create_index(batch_op.f('idx_account_id'), ['account_id'], unique=False)

    op.create_table('llmops_workflow',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的用户id'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='工作流名称'),
    sa.Column('tool_call_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='工作流调用名称'),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='工作流图标'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='工作流描述'),
    sa.Column('graph', mysql.JSON(), nullable=False, comment='工作流图结构信息'),
    sa.Column('draft_graph', mysql.JSON(), nullable=False, comment='工作流草稿图'),
    sa.Column('is_debug_passed', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='调试是否通过'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='工作流状态'),
    sa.Column('published_at', mysql.TIMESTAMP(), nullable=True, comment='发布时间'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('api_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='API密钥'),
    sa.PrimaryKeyConstraint('id'),
    comment='工作流模型',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='工作流模型',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_workflow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('api_key'), ['api_key'], unique=True)

    op.create_table('llmops_api_tool',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的用户id'),
    sa.Column('provider_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的提供者id'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='工具名称'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='工具描述'),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='工具API地址'),
    sa.Column('method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='路由方法'),
    sa.Column('parameters', mysql.JSON(), nullable=True, comment='工具参数'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='API工具',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='API工具',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_api_tool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_account_name'), ['account_id', 'name'], unique=True)
        batch_op.create_index(batch_op.f('idx_account_id'), ['account_id'], unique=False)

    op.create_table('llmops_message',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('app_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='应用id'),
    sa.Column('conversation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='会话id'),
    sa.Column('invoke_from', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='调用来源'),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='创建账号id'),
    sa.Column('query', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='消息的原始问题'),
    sa.Column('message', mysql.JSON(), nullable=False, comment='最终消息列表'),
    sa.Column('message_token_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='token数'),
    sa.Column('message_unit_price', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=False, comment='单价'),
    sa.Column('message_price_unit', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=False, comment='价格单位'),
    sa.Column('answer', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='AI内容消息'),
    sa.Column('answer_token_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='token数'),
    sa.Column('answer_unit_price', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=False, comment='单价'),
    sa.Column('answer_price_unit', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=False, comment='价格单位'),
    sa.Column('latency', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=False, comment='响应耗时'),
    sa.Column('total_token_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='总token数'),
    sa.Column('total_price', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=False, comment='消息总价格'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='状态'),
    sa.Column('error', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='错误日志'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='消息表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='消息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_app_id'), ['app_id'], unique=False)

    op.create_table('llmops_segment',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的用户id'),
    sa.Column('dataset_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的知识库id'),
    sa.Column('document_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的文档id'),
    sa.Column('node_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='向量数据库节点id用于快速查找'),
    sa.Column('position', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='片段在文档的位置'),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='片段内容'),
    sa.Column('character_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='片段长度'),
    sa.Column('token_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='token词数'),
    sa.Column('keywords', mysql.JSON(), nullable=True, comment='关键词列表'),
    sa.Column('hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='内容哈希值'),
    sa.Column('hit_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='命中次数'),
    sa.Column('enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否启用'),
    sa.Column('disabled_at', mysql.TIMESTAMP(), nullable=True, comment='禁用时间'),
    sa.Column('processing_started_at', mysql.TIMESTAMP(), nullable=True, comment='开始处理时间'),
    sa.Column('index_completed_at', mysql.TIMESTAMP(), nullable=True, comment='索引结束时间'),
    sa.Column('completed_at', mysql.TIMESTAMP(), nullable=True, comment='构建完成时间'),
    sa.Column('stopped_at', mysql.TIMESTAMP(), nullable=True, comment='停止时间'),
    sa.Column('error', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='错误日志'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("'waiting'"), nullable=False, comment='状态（如 waiting/processing/completed）'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文档片段',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='文档片段',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_segment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_hash'), ['hash'], unique=True)
        batch_op.create_index(batch_op.f('idx_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_account_id'), ['account_id'], unique=False)

    op.create_table('llmops_chat_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='聊天id'),
    sa.Column('role', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='角色类型，1:assist，2:user'),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='租户id'),
    sa.Column('dialog_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='对话id'),
    sa.Column('content', mysql.JSON(), nullable=True, comment='对话内容'),
    sa.Column('token', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='token数'),
    sa.Column('creator', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64), server_default=sa.text("''"), nullable=False, comment='创建人'),
    sa.Column('ctime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='对话记录表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='对话记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_chat_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_role'), ['role'], unique=False)

    op.create_table('llmops_upload_file',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='上传文件的用户id'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='上传的文件名'),
    sa.Column('key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='对象存储文件路径'),
    sa.Column('size', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='上传文件的大小'),
    sa.Column('extension', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='文件扩展名'),
    sa.Column('mime_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='mimetype'),
    sa.Column('hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='文件内容的哈希值'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='上传文件',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='上传文件',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('llmops_app_config',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('app_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的应用id'),
    sa.Column('model_config', mysql.JSON(), nullable=False, comment='模型配置'),
    sa.Column('dialog_round', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='上下文对话轮数'),
    sa.Column('preset_prompt', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='人设与回复逻辑'),
    sa.Column('tools', mysql.JSON(), nullable=False, comment='关联工具列表'),
    sa.Column('workflows', mysql.JSON(), nullable=False, comment='关联工作流列表'),
    sa.Column('retrieval_config', mysql.JSON(), nullable=False, comment='知识库检索配置'),
    sa.Column('long_term_memory', mysql.JSON(), nullable=False, comment='长期记忆配置'),
    sa.Column('opening_statement', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='对话开场白'),
    sa.Column('opening_questions', mysql.JSON(), nullable=False, comment='开场建议问题'),
    sa.Column('suggested_after_answer', mysql.JSON(), nullable=False, comment='回答后建议问题'),
    sa.Column('speech_to_text', mysql.JSON(), nullable=False, comment='语音转文本配置'),
    sa.Column('text_to_speech', mysql.JSON(), nullable=False, comment='文本转语音配置'),
    sa.Column('review_config', mysql.JSON(), nullable=False, comment='内容审核配置'),
    sa.Column('config_type', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='配置类型'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='应用配置表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='应用配置表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_app_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_app_config_type'), ['app_id', 'config_type'], unique=False)

    op.create_table('llmops_dataset',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的用户id'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='知识库名称'),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='知识库图标'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='知识库描述'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='知识库',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='知识库',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_account_name'), ['account_id', 'name'], unique=True)
        batch_op.create_index(batch_op.f('idx_account_id'), ['account_id'], unique=False)

    op.create_table('llmops_process_rule',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的用户id'),
    sa.Column('dataset_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='归属的知识库id'),
    sa.Column('mode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("''"), nullable=False, comment='处理模式'),
    sa.Column('rule', mysql.JSON(), nullable=True, comment='处理规则'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='处理规则表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='处理规则表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_process_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('idx_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_account_id'), ['account_id'], unique=False)

    op.create_table('llmops_api_key',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('account_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的用户id'),
    sa.Column('api_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='API密钥'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否激活'),
    sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='备注信息'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='API密钥表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='API密钥表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uniq_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('idx_account_id'), ['account_id'], unique=False)

    op.create_table('llmops_dataset_query',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('dataset_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的知识库id'),
    sa.Column('query', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='查询query语句'),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='查询的来源'),
    sa.Column('source_app_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='查询关联的应用id'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='知识库查询',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='知识库查询',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_dataset_query', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_source_app_id'), ['source_app_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)

    op.create_table('llmops_chat_dialog',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='兑换id'),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False, comment='对话概要'),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='租户id'),
    sa.Column('content', mysql.JSON(), nullable=True, comment='对话内容'),
    sa.Column('creator', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64), server_default=sa.text("''"), nullable=False, comment='创建人'),
    sa.Column('operator', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64), server_default=sa.text("''"), nullable=False, comment='最后修改人'),
    sa.Column('ctime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('utime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='对话概要表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='对话概要表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_chat_dialog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('llmops_app_dataset_join',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('app_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的应用id'),
    sa.Column('dataset_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text("''"), nullable=False, comment='关联的知识库id'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='应用关联知识库表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='应用关联知识库表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_app_dataset_join', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_app_dataset'), ['app_id', 'dataset_id'], unique=True)

    op.create_table('llmops_account',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='主键UUID'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='账号名称'),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='绑定邮箱（唯一）'),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='密码哈希值（非明文）'),
    sa.Column('password_salt', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='密码盐值'),
    sa.Column('assistant_conversation_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True, comment='关联的辅助会话ID'),
    sa.Column('last_login_at', mysql.TIMESTAMP(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), server_default=sa.text("''"), nullable=False, comment='最后登录IP（支持IPv6）'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=True, comment='头像'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户账号表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='用户账号表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llmops_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uniq_email'), ['email'], unique=True)

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_index('idx_app_account_id')

    op.drop_table('app')
    # ### end Alembic commands ###
