#!/usr/bin/eny python
# -*- coding: utf-8 -*-
"""
@Time    :2025/6/22 21:00
#Author  :Emcikem
@File    :1-LLM链
"""
import dotenv
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from langchain_core.runnables import ConfigurableField

dotenv.load_dotenv()

prompt = ChatPromptTemplate.from_template("{query}")
llm = ChatOpenAI(model="deepseek-chat").configurable_alternatives(
    ConfigurableField(id="llm"),
    default_key="deepseek-chat",
    deepseek=ChatOpenAI(model="deepseek-reasoner"),
    deepseek2=ChatOpenAI(model="deepseek-chat")
)

chain = prompt | llm | StrOutputParser()

content = chain.invoke(
    {"query": "你好，你是什么模型"},
    config={"configurable": {"llm": "deepseek2"}}
)
print(content)